---
title: "R Notebook"
author: "Kevin Stachelek"
date: "12/04/2018"
output: html_notebook
runtime: shiny
---

```{r setup, echo=F}
knitr::opts_chunk$set(echo = F)
```

```{r load-libraries, message=F, warning=F}
# load required libraries -------------------------------------------------
library(optparse)
suppressMessages(library(tidyverse))
suppressMessages(library(gtools))
suppressMessages(library(EnsDb.Hsapiens.v86))
library(ensembldb)
edb <- EnsDb.Hsapiens.v86
library(SingleCellExperiment)
library(cataract)
library(annotables)
library(gtools)
library(here)

```


```{r load-functions}

sce_from_tibbles <- function(counts, census_counts, colData){
	featuredata <- data.frame(counts[,1])
	rownames(featuredata) <- featuredata[,1]
	
	counts <- tibble::column_to_rownames(counts, colnames(counts)[1]) %>% 
	  as.matrix()
	
	census_counts <- tibble::column_to_rownames(census_counts, colnames(census_counts)[1])

	# check that dimensions of counts and census counts are equal and in same order
	census_missing_cells <- colnames(counts)[!colnames(counts) %in% colnames(census_counts)]
	census_counts[census_missing_cells] <- "NA"
	census_counts <- census_counts[rownames(counts),colnames(counts)] %>% 
		as.matrix()
		
	# check that colData and counts contain same cells
	colData <- data.frame(colData)
	rownames(colData) <- colData[,1]
	colData <- colData[colnames(counts),]
	

	
	sumexp <- SummarizedExperiment(assays=list(counts=counts, census_counts=census_counts), colData=colData, rowData=featuredata)
	
	# filter out cells not in comparison
	sce <- sce <- as(sumexp, "SingleCellExperiment")
	
	return(sce)
}

find_remove_cells <- function(plot_settings, annotation){
  # browser()
  test <- readLines(plot_settings)
  
  # if (!grepl('remove', test)){
  #   return(NULL)
  # }
  
  vecs <- list()
  mtnames <- c()
  for (i in test){
    if (!grepl("#", i) & grepl('remove', i)){
      lbline = strsplit(i, "\t")
      d = unlist(lbline)[[2]]
      vecs <- append(vecs, lbline)
      # add treatment prefix
      if (d %in% c("shCtrl", "sh733", "sh737")){
        d <- paste0("treatment_", d)
      }

      mtnames <- append(mtnames, d) 
      
    }
  }
  
 

  
  pfx <- tolower(gsub("_.*", "", mtnames))
  valid_pfx  <- which(pfx %in% tolower(colnames(annotation)))
  
  if (length(valid_pfx) == 0){
    return(NULL)
  }
  
  which(pfx %in% annotation$treatment_group)
  
  pfx <- pfx[valid_pfx]
  
  sfx <- gsub(".*_", "", mtnames[valid_pfx])
  
  remove_cells <- purrr::map2(pfx, sfx , function(x, y) annotation[annotation[tolower(x)] == y,])
  
  
  
  remove_cells <- dplyr::bind_rows(remove_cells)
  
  ind <- apply(remove_cells, 1, function(x) all(is.na(x)))
  remove_cells <- remove_cells[ !ind, ]
  
  remove_cells <- unique(remove_cells[,1])
  
}


match_cols <- function(match_vecs, sv_name){
  # browser()
  out=NULL
  for (i in match_vecs){
    vetor <- i
    vetor <- vetor[vetor != ""]
    key <- data.frame(sample_id=vetor[-1], sv_name=rep(gsub(".*_","", vetor[[1]]), (length(vetor)-1)))  
    out <- rbind(out, key)
  }  
  colnames(out) <- c("sample_id", sv_name) 
  return(out)
}

convert_mt_setting <- function(cell_settings, plot_settings){
  # browser()
  test <- readLines(cell_settings)
  # drop blank lines
  test <- test[grepl(".*", test)]
  vecs <- list()
  mtnames <- c()
  for (i in test){
    if (!grepl("#", i)){
      lbline = strsplit(i, "\t")
      d = unlist(lbline)[[1]]
      vecs <- append(vecs, lbline)
      mtnames <- append(mtnames, d)    
    }
    
  }
  # browser()
  # add treatment group label to conform to formatting of other tags
  treatment_ind <- which(mtnames %in% c("shCtrl", "sh733", "sh737"))
  mtnames[treatment_ind] <- paste0("treatment_", mtnames[treatment_ind])
  
  pfx <- unique(gsub("_.*", "", mtnames[grep("_", mtnames)]))
  pfx <- paste0(pfx, "_")
  test <- list()
  for (i in pfx){
    test1 <- list(which(startsWith(mtnames, i)))
    names(test1) = tolower(gsub("_", "", i))
    test <- append(test, test1)
  }
  
  sub_vecs <- list()
  vec_names <- list()
  for (i in test){

    test_vec <- vecs[i]
    sub_vecs <- append(sub_vecs, list(test_vec))
  }
  
  # names(sub_vecs) <- vec_names[1:length(sub_vecs)]
  names(sub_vecs) <- names(test)
  
  sub_vecs <- sub_vecs[unlist(lapply(sub_vecs, length) != 0)]
  
  param_dfs <- purrr::map2(sub_vecs, names(sub_vecs), match_cols)
  
  
  
  if (is.list(param_dfs) & length(param_dfs) != 0) {
    # browser()
    param_dfs <- param_dfs %>%
      Reduce(function(dtf1,dtf2) dplyr::full_join(dtf1,dtf2,by="sample_id"), .) %>% 
      dplyr::arrange(sample_id)  
    
    dup_cells <- which(duplicated(param_dfs[,1]))
    if (any(dup_cells)){
      print(paste0("cells ", paste(param_dfs$sample_id[dup_cells], collapse = " "), " found duplicated in cell sets! They will be removed from analysis"))
      param_dfs <- param_dfs[-dup_cells,]
    }
    
    rownames(param_dfs) <- param_dfs[,1]
    
  }
  
  remove_cells <- find_remove_cells(plot_settings, param_dfs)
  
  
  return(list("annotation" = param_dfs, "removed_cells" = remove_cells))
  
}

take_input <- function(prompt = question, interactive = FALSE){
  if(interactive){
    param <- readline(prompt=question)
  } else {
    param <- readLines("stdin", n=1)
  }
  return(param)
}

plot_trx_old <- function(transcript, sce, x_axis, facet){
  # browser()
	filt_cm <- census_matrix[rownames(census_matrix) %in% transcript,]
  filt_cm <- tidyr::gather(filt_cm, "sample_id", "counts") %>% 
    inner_join(annotation)
  filt_cm <- filt_cm[!is.na(filt_cm[[facet]]),]
  new_levels <- mixedsort(levels(filt_cm[[facet]]))
  filt_cm[[facet]] <- factor(filt_cm[[facet]], levels = new_levels)
  
  RBKD_filt_cm <- filt_cm %>% 
    dplyr::filter(treatment_group %in% c("sh733", "sh737", "sh842")) %>% 
    dplyr::mutate(treatment_group = "RBKD")
  
  comb_filt_cm <- rbind(RBKD_filt_cm, filt_cm)
  
  if(any(comb_filt_cm$day %in% c("day_15"))){
      comb_filt_cm <- dplyr::mutate(comb_filt_cm, day = dplyr::case_when(
        day == "day_3" | day == "day_5" ~ "day 3-5",
        day == "day_7" | day == "day_9" ~ "day 7-9",
        day == "day_12" | day == "day_15" ~ "day 12-15",
        TRUE ~ as.character(day)
      ))
  }
  
  comb_filt_cm <- comb_filt_cm[!is.na(comb_filt_cm$day),]
  
  comb_filt_cm$day <- factor(comb_filt_cm$day, levels <- unique(comb_filt_cm$day))
  # comb_filt_cm$day <- factor(comb_filt_cm$day, levels = c("RBKD", levels(filt_cm$treatment_group)))
  # comb_filt_cm$treatment_group <- factor(comb_filt_cm$treatment_group, levels = c("RBKD", levels(filt_cm$treatment_group)))

  bplot <- ggplot(data = comb_filt_cm, aes_string(x=facet, y="counts")) + 
    geom_boxplot() +
    geom_jitter(height = 0, width = 0.1) +
    # scale_x_discrete(mixedsort(levels(filt_cm[[facet]]))) +
    facet_grid(. ~ treatment_group) + 
    theme(axis.text.x=element_text(angle=90, hjust=1)) +
    labs(title = lookup_genes(transcript), subtitle = transcript)

  return(bplot)
}

lookup_transcripts_from_symbols <- function(symbols, annotable = annotables::grch38, t2g = annotables::grch38_tx2gene){    
	# browser()
	
	trx <- dplyr::filter(annotable, symbol %in% symbols) %>% 
		dplyr::inner_join(t2g, by = "ensgene") %>% 
		dplyr::pull(enstxp)
	
	return(trx)
	
}

plot_trx_by_axis_and_facet <- function(transcript, sce, x, y = counts, facet, symbol = NULL, count_type = "counts"){
	# browser()
	
	x_var <- sym(x)
  facet_var <- sym(facet)

	tidy_counts <- as_tibble(assay(sce[transcript,], count_type)) %>% 
		tidyr::gather("Sample_ID", "counts") %>% 
		dplyr::full_join(as_tibble(colData(sce)), by = "Sample_ID") %>% 
		dplyr::mutate(!!x_var := factor(!!x_var, levels = gtools::mixedsort(unique(!!x_var)))) %>%
		dplyr::mutate(!!facet_var := factor(!!facet_var, levels = gtools::mixedsort(unique(!!facet_var)))) %>%
		dplyr::mutate(counts = as.numeric(counts)) %>% 
		identity()
	# facet_levels <- gtools::mixedsort(tidy_counts[[!!facet_var]])
	
	p <- ggplot(tidy_counts, aes(x= !!x_var, y = counts)) + 
		geom_boxplot() +
		facet_grid(cols = vars(!!facet_var)) + 
		labs(title = symbol, subtitle = transcript)
	
	print(p)
	
}

# onev <- "day"
# 
# twov <- "treatment_group"
# 
# plot_trx_by_axis_and_facet(transcript, sce, x = onev, facet = twov, symbol = "RXRG")

plot_gene_summed_trx <- function(sce, symbol, x, facet){
  # browser()
	
	x_var <- ensym(x)
	facet_var <- ensym(facet)
	
	trx <- lookup_transcripts_from_symbols(symbol)
	
	bplots <- lapply(trx, plot_trx_by_axis_and_facet, sce, 
									 x = !!x_var,
									 facet = !!facet_var,
									 symbol = symbol)
	
  return(bplots)
}

# plot_gene_summed_trx(sce, "RXRG", "day", "treatment_group")

```

```{r file-paths}

# load data ------------------------------------------------------

counts_paths <- c("~/single_cell_projects/quicklinks/FACS_20170407_dshayler_H_sapiens_proj/output/stringtie_transcripts_raw_counts.csv",
	"~/single_cell_projects/quicklinks/FACS_20171031_dshayler_H_sapiens_proj/output/stringtie_transcripts_raw_counts.csv",
	"~/single_cell_projects/quicklinks/FACS_20181001_dshayler_Organoid_proj/output/transcript_count_matrix_fetal.csv", 
	"~/single_cell_projects/quicklinks/FACS_20170407_sunlee_H_sapiens_proj/output/Sunhye_stringtie.tpm.csv",
									 "~/single_cell_projects/quicklinks/FACS_20171031_sunlee_H_sapiens_proj/output/transcripts.tpm.csv")

census_paths <- c("~/single_cell_projects/quicklinks/FACS_20170407_dshayler_H_sapiens_proj/output/transcripts_tpm_census_matrix.csv",
                  "~/single_cell_projects/quicklinks/FACS_20171031_dshayler_H_sapiens_proj/output/transcripts_tpm_census_matrix.csv",
                  "~/single_cell_projects/quicklinks/FACS_20181001_dshayler_Organoid_proj/output/fetal_census_matrix.csv",
									"~/single_cell_projects/quicklinks/FACS_20170407_sunlee_H_sapiens_proj/output/FACS_20170407_sunlee_H_sapiens_census_matrix.csv",
									"~/single_cell_projects/quicklinks/FACS_20171031_sunlee_H_sapiens_proj/output/FACS_20171031_sunlee_H_sapiens_census_matrix.csv")

GROUP_PATHS <- c("~/single_cell_projects/quicklinks/FACS_20170407_dshayler_H_sapiens_proj/cell_metadata.csv",
								 "~/single_cell_projects/quicklinks/FACS_20171031_dshayler_H_sapiens_proj/FACS_20171031_dshayler_sample_sheet.csv",
								 "~/single_cell_projects/quicklinks/FACS_20181001_dshayler_Organoid_proj/10_2018_Seq_3_fetal_cell_metadata.csv",
								 "~/single_cell_projects/quicklinks/FACS_20170407_sunlee_H_sapiens_proj/output/Sunhye_cell_division_day_treatment.csv",
										"~/single_cell_projects/quicklinks/FACS_20171031_sunlee_H_sapiens_proj/output/FACS_20171031_sunlee_sample_sheet.csv")

expids <- c("ds20170407",
						"ds20171031",
						"ds20181001",
						"shl20170407",
						"shl20171031")

rds_paths <- paste0("/home/skevin/ShinyApps/single_cell_boxplot/", expids, ".rds")

outdir = "~/single_cell_projects/quicklinks/3_seq_dshayler_proj/output/mnncorrect"
```

```{r read-data, eval=F}

counts <- purrr::map(counts_paths, read_csv)
census_counts <- purrr:::map(census_paths, read_csv)

colData <- purrr::map(GROUP_PATHS, read_csv)

	
sce_in <- list(counts = counts, census_counts = census_counts, colData = colData)
# sces <- purrr::pmap(sce_in, sce_from_tibbles)

names(sces) <- expids

purrr::map2(sces, rds_paths, saveRDS)

```

```{r load-data-2, eval=F}

sces <- purrr::map(rds_paths, readRDS)
names(sces) <- expids

# # we exclude "removed cells (as defined by wetlab user)
# ds_removed <- "~/single_cell_tools/dshayler_input/3_Fetal_Seq/removed_cells.txt"
# wetlab_removed <- ds_removed
# wetlab_removed <- readr::read_lines(wetlab_removed)
# 
# sces <- lapply(sces, function(x) x[,!colnames(x) %in% wetlab_removed])
# 
# names(sces) <- c("batch_1", "batch_2", "batch_3")
# 
# subset_sces_by_cell <- function(keep_cells, batch){
#   batch <- lapply(batch, function(x) x[,colnames(x) %in% keep_cells])
#   return(batch)
# }

# sces_clusts <- lapply(cluster_cells, subset_sces_by_cell, sces)

```

```{r}
selectInput("experiment", "Experiment:",
						c("DS 1st experiment" = "ds20170407",
						"DS 2nd experiment" = "ds20171031",
						"DS 3rd exeriment" = "ds20181001",
						"SHL 1st experiment" = "shl20170407",
						"SHL 2nd experiment" = "shl20171031"), selected = "shl20170407" )

```

```{r}
actionButton("loadButton", "Load Dataset")
```


```{r}

 sce <- eventReactive(input$loadButton, { 
		sce <- readRDS(paste0(here(), "/single_cell_boxplot/", input$experiment, ".rds"))
    # sce <- sces0[[input$experiment]]
    sce
    })

```

```{r}
output$x_axis <- renderUI({
  sce_cd <- colnames(colData(sce()))
  radioButtons(inputId = "x_axis", label = "X axis variable", choices = sce_cd)
})

output$facet <- renderUI({
  sce_cd <- colnames(colData(sce()))
	radioButtons(inputId = "facet", label = "facet variable", choices = sce_cd)
})

uiOutput("x_axis")

uiOutput("facet")
```

```{r}
textInput("feature", label = "gene or set of genes to plot (separated by ', '): ",
               value = "RXRG")
```

```{r, eval = T}
radioButtons(inputId = "assay", label = "count type:", choices = c("raw" = "counts", "census" = "census_counts"))
```


```{r}
actionButton("goButton", "Go!")
```

```{r}
observeEvent(input$loadButton, {
    session$sendCustomMessage(type = 'testmessage',
      message = 'Dataset loaded')
  })
```


```{r, eval = T}

trx<- eventReactive(input$goButton, {
	transcripts <- lookup_transcripts_from_symbols(input$feature)
	transcripts
	})

# renderText(trx())

```

```{r, eval = T}
p_list <- eventReactive(input$goButton, {
	
	# trx<- lookup_transcripts_from_symbols(input$feature)
	# trx <- lookup_transcripts_from_symbol(input$feature)
	
	# trx <- lookup_transcripts_from_symbols(input$feature)
	
	# trx <- trx()
	
	# trx <- c("ENST00000359842", "ENST00000470566", "ENST00000465764", "ENST00000619224")
	
	sce0 <- sce()
	
	# sce0 <- SummarizedExperiment::assay(sce0)[trx(),]
	
	p_list <- lapply(trx(), plot_trx_by_axis_and_facet, sce0, x = input$x_axis, facet = input$facet, symbol = input$feature, count_type = input$assay)
	p_list
})

renderUI({
	plot_output_list <- lapply(1:length(p_list()), function(i) {
		plotname <- paste("plot", i, sep="")
		plotOutput(plotname)
	})
	do.call(tagList, plot_output_list)
})

observe({
for (i in 1:length(p_list())) {
    local({
        my_i <- i
        plotname <- paste("plot", my_i, sep="")
        output[[plotname]] <- renderPlot({
            p_list()[[my_i]]
        })
    })
}
})
```




